default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Qwertyui@143
  

development:
  <<: *default
  database: project_management_2

test:
  <<: *default
  database: project_management_2_test

production:
  <<: *default
  database: project_management_2
  username: root
  password: Qwertyui@143
  host: localhost
